sizes: [6, 2, 1]
learning_rate: 0.0005
activation_function: ["tanh", "ReLU", "sigmoid"]
loss_function: "BCE" # MSE, BCE, CE
gradient_type: "SGD"
epochs: 80
data_path: "./data/data.csv"
batch_size: 100